// Generated by CoffeeScript 2.6.1
(function() {
  // Event handler for the donation form submission
  document.addEventListener('DOMContentLoaded', function() {
    var donateForm;
    donateForm = document.querySelector('#donate-form');
    if (donateForm) {
      return donateForm.addEventListener('submit', function(event) {
        var amount, email, name;
        event.preventDefault(); // Prevent the default form submission
        
        // Get form data
        amount = donateForm.querySelector('#amount' != null ? '#amount'.value : void 0);
        name = donateForm.querySelector('#name' != null ? '#name'.value : void 0);
        email = donateForm.querySelector('#email' != null ? '#email'.value : void 0);
        // Validate form fields
        if (amount && name && email) {
          // Simulate form submission
          return fetch('/donate', { // Your server endpoint
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              amount: amount,
              name: name,
              email: email
            })
          }).then(function(response) {
            if (response.ok) {
              return response.json();
            } else {
              throw new Error('Failed to submit donation');
            }
          }).then(function(data) {
            // Handle success response
            alert('Thank you for your donation!');
            return donateForm.reset();
          }).catch(function(error) {
            // Handle error response
            return alert('An error occurred: ' + error.message);
          });
        } else {
          return alert('Please fill out all fields.');
        }
      });
    }
  });

}).call(this);
