name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  setup-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'  # specify your Go version
    - run: go version

  setup-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # specify your Java version
        distribution: 'adoptopenjdk'
    - run: java -version

  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Close Stale Issues
      uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        stale-issue-label: 'stale'
        close-issue-label: 'closed'
        days-before-pr-stale: 60
        days-before-pr-close: 7
        stale-pr-label: 'stale'
        close-pr-label: 'closed'
